services:
  fdb:
    container_name: fdb
    image: foundationdb/foundationdb:7.3.62
    volumes:
      - type: volume
        source: dbdata
        target: /var/fdb/
    ports:
      - 4500:4500

volumes:
  dbdata:
